/*Herein lies all the action types*/

//action types for login
export const login = {
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',
	SET_REDIRECT: 'SET_REDIRECT',
	DEVELOPER_DETAILS: 'DEVELOPER_DETAILS'
};

//action types for editor
export const editor = {
	FILE_OPEN: 'FILE_OPEN',
	CLOSE_FILE: 'CLOSE_FILE',
	SWITCH_TAB: 'SWITCH_TAB',
	CLEAR_TABS: 'CLEAR_TABS',
	CHANGE_CODE: 'CHANGE_CODE',
	FILESOURCE_FETCHING: 'FILESOURCE_FETCHING',
	FILESOURCE_ERROR: 'FILESOURCE_ERROR',
	FILESOURCE_UPDATING: 'FILESOURCE_UPDATING',
	FILESOURCE_UPDATEERROR: 'FILESOURCE_UPDATEERROR',
	FILESOURCE_UPDATED: 'FILESOURCE_UPDATED',
	FILESOURCE_COMPILING: 'FILESOURCE_COMPILING',
	FILESOURCE_COMPILED: 'FILESOURCE_COMPILED',
	FILE_CHANGED: 'FILE_CHANGED',
	IS_OPEN: 'IS_OPEN',
	FILE_DELETE: 'FILE_DELETE',
	UPDATE_FILETYPE: 'UPDATE_FILETYPE',
	FILE_DELETING: 'FILE_DELETING',
	FILE_DELETED: 'FILE_DELETED',
	MAKING_PAGEDEFAULT: 'MAKING_PAGEDEFAULT',
	MADE_PAGEDEFAULT: 'MADE_PAGEDEFAULT',
	MAKE_PAGEDEFAULTERROR: 'MAKE_PAGEDEFAULTERROR',
	SET_HELPER: 'SET_FILE_HELPER',
	UPDATE_RENAMEFILE: 'UPDATE_RENAMEFILE'
};

//action types for project tree
export const projectree = {
	PROJECT_FETCHING: 'PROJECT_FETCHING',
	PROJECT_RECEIVED: 'PROJECT_RECEIVED',
	PROJECT_INIT: 'PROJECT_INIT',
	PROJECT_GETINIT: 'PROJECT_GETINIT',
	PROJECT_UPDATE: 'PROJECT_UPDATE',
	PROJECT_CREATING: 'PROJECT_CREATING',
	PROJECT_EDITING: 'PROJECT_EDITING',
	PROJECT_PUBLISHING: 'PROJECT_PUBLISHING',
	UPDATE_MAPPEDSCHEMA: 'UPDATE_MAPPEDSCHEMA',
	COMPONENTS_FETCHED: 'COMPONENTS_FETCHED',
	UPDATE_COMPONENT: 'UPDATE_COMPONENT',
	COMPONENTS_MAP: 'COMPONENTS_MAP',
	PROJECT_DELETENODE: 'PROJECT_DELETENODE',
	UPDATE_PROJECTDATA: 'UPDATE_PROJECTDATA',
	UPDATE_PROJECTNAME: 'UPDATE_PROJECTNAME',
	UPDATE_PROJECTREENODE: 'UPDATE_PROJECTREENODE',
	UPDATE_RENAMENODE: 'UPDATE_RENAMENODE',
	SET_ACTIVEGATEWAY: 'SET_ACTIVEGATEWAY',
	APPLICATION_ZIP_UPLOAD_COMPLETE: 'APPLICATION_UPLOAD_COMPLETE'
};

export const existingAppDeploymentType = {
	CONTAINERISE: 'CONTAINER_FOR_CAAS',
	USE_AS_ENDPOINT: 'HYBRID_CLOUD'
};

//action types for react-modal
export const modals = {
	MODAL_OPEN: 'MODAL_OPEN',
	MODAL_CLOSE: 'MODAL_CLOSE',
	MODAL_THEMESFETCHING: 'MODAL_THEMESFETCHING',
};

//action types for page-state
export const pages = {
	PAGESTATE_UPDATE: 'PAGESTATE_UPDATE'
};

//action types for footer
export const footer = {
	FOOTER_INIT: 'FOOTER_INIT',
	UPDATE_NOTIFICATION: 'UPDATE_NOTIFICATION',
	UPDATE_LOG: 'UPDATE_LOG',
	FOOTER_COLLAPSE: 'FOOTER_COLLAPSE',
	SAVE_LOG: 'SAVE_LOG',
	FOOTER_APPEND: 'FOOTER_APPEND',
	FOOTER_REMOVE: 'FOOTER_REMOVE',
	FOOTER_UPDATEUPLOAD: 'FOOTER_UPDATEUPLOAD',
	FOOTER_RESETLOG: 'FOOTER_RESETLOG'
};

//action types for LoadingBar
export const loader = {
	LOADER_SHOW: 'LOADER_SHOW',
	LOADER_HIDE: 'LOADER_HIDE'
};

// action types for upload functionality
export const upload = {
	SET_FAILED: 'SET_FAILED',
	SET_PATH: 'SET_PATH',
	UPDATE_FILES: 'UPDATE_FILES',
	UPDATE_APPLICATION_FILES: 'UPDATE_APPLICATION_FILES',
	RESET_STORE: 'RESET_STORE',
	UPLOAD: 'UPLOAD',
	UPLOADING: 'UPLOADING',
	UPLOADED: 'UPLOADED',
	UPLOAD_ERROR: 'UPLOAD_ERROR',
	RESET_FAILED: 'RESET_FAILED'
};

//action types for project tree
export const build = {
	SET_RETRY: 'SET_RETRY',
	BUILDING: 'BUILDING',
	BUILD_COMPLETE: 'BUILD_COMPLETE',
	SET_STAGE: 'SET_STAGE'
};

//action types for customerList
export const customer = {
	CUSTOMER_RECEIVED: 'CUSTOMER_RECEIVED'
};

//action types for schemaCreator
export const schemaCreator = {
	OPEN_SCHEMA: 'OPEN_SCHEMA',
	RESET: 'RESET',
	SCHEMA_SETDEFAULT: 'SCHEMA_SETDEFAULT',
	SCHEMAS_FETCHING: 'SCHEMAS_FETCHING',
	SCHEMAS_FETCHED: 'SCHEMAS_FETCHED',
	SCHEMAS_FETCHERROR: 'SCHEMAS_FETCHERROR',
	SCHEMADETAILS_FETCHING: 'SCHEMADETAILS_FETCHING',
	SCHEMADETAILS_FETCHED: 'SCHEMADETAILS_FETCHED',
	SCHEMADETAILS_FETCHERROR: 'SCHEMADETAILS_FETCHERROR',
	SCHEMA_CREATING: 'SCHEMA_CREATING',
	SCHEMA_CREATED: 'SCHEMA_CREATED',
	SCHEMA_CREATEERROR: 'SCHEMA_CREATEERROR',
	SCHEMA_SAVING: 'SCHEMA_SAVING',
	SCHEMA_SAVED: 'SCHEMA_SAVED',
	SCHEMA_SAVEERROR: 'SCHEMA_SAVEERROR',
	SET_HELPER: 'SET_SCHEMA_HELPER',
	CREATE_SYSDEFLANG: 'CREATE_SYSDEFLANG',
	ADD_SYSDEFLANG: 'ADD_SYSDEFLANG',
	DEL_SYSDEFLANG: 'DEL_SYSDEFLANG',
	RESET_SYSDEF: 'RESET_SYSDEF',
	SET_SUPPORTED_META: 'SET_SUPPORTED_META',
	HAS_WEBSITE_DATA: 'HAS_WEBSITE_DATA'
};

//action types for WebForm
export const webForm = {
	IS_WEBFORMOPEN: 'IS_WEBFORMOPEN',
	WEBFORMS_FETCHING: 'WEBFORMS_FETCHING',
	WEBFORMS_FETCHED: 'WEBFORMS_FETCHED',
	WEBFORMS_FETCHERROR: 'WEBFORMS_FETCHERROR',
	SET_CURRENT: 'SET_CURRENT',
	SET_CURRENT_PROPERTIES: 'SET_CURRENT_PROPERTIES',
	CREATE_WEBFORM: 'CREATE_WEBFORM',
	SET_NEW_DETAILS: 'SET_NEW_DETAILS',
	SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
	INITIALIZE: 'INITIALIZE',
	SET_MODIFIED: 'SET_MODIFIED',
	SET_HELPER: 'SET_WEBFORM_HELPER',
	SET_IS_EDITABLE: 'SET_IS_EDITABLE',
	CAN_CLONE: 'CAN_CLONE',
	JSON_WEBFORM: 'JSON_WEBFORM'
};

export const serverMaintenance = {
	UPDATE_SERVER_DETAILS: 'UPDATE_SERVER_DETAILS'
}
