// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

package routing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Route struct {
	Pattern              string   `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Filepath             string   `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Filetype             string   `protobuf:"bytes,3,opt,name=filetype,proto3" json:"filetype,omitempty"`
	ResourceId           string   `protobuf:"bytes,4,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	IsStatic             bool     `protobuf:"varint,5,opt,name=isStatic,proto3" json:"isStatic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_678feabaa613e30f, []int{0}
}
func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (dst *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(dst, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *Route) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *Route) GetFiletype() string {
	if m != nil {
		return m.Filetype
	}
	return ""
}

func (m *Route) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *Route) GetIsStatic() bool {
	if m != nil {
		return m.IsStatic
	}
	return false
}

type Node struct {
	Root                 bool     `protobuf:"varint,1,opt,name=root,proto3" json:"root,omitempty"`
	Segment              string   `protobuf:"bytes,2,opt,name=segment,proto3" json:"segment,omitempty"`
	Route                *Route   `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	Children             []*Node  `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_678feabaa613e30f, []int{1}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetRoot() bool {
	if m != nil {
		return m.Root
	}
	return false
}

func (m *Node) GetSegment() string {
	if m != nil {
		return m.Segment
	}
	return ""
}

func (m *Node) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *Node) GetChildren() []*Node {
	if m != nil {
		return m.Children
	}
	return nil
}

func init() {
	proto.RegisterType((*Route)(nil), "routing.Route")
	proto.RegisterType((*Node)(nil), "routing.Node")
}

func init() { proto.RegisterFile("models.proto", fileDescriptor_models_678feabaa613e30f) }

var fileDescriptor_models_678feabaa613e30f = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x65, 0x9a, 0xd0, 0x70, 0x05, 0x86, 0x9b, 0x2c, 0x06, 0x14, 0x55, 0x0c, 0x61, 0xc9,
	0x50, 0x9e, 0x82, 0x85, 0xc1, 0x3c, 0x41, 0x48, 0x8e, 0xd6, 0x52, 0x9a, 0xb3, 0xec, 0xcb, 0xc0,
	0x03, 0xf0, 0x08, 0xbc, 0x2f, 0xb2, 0x9b, 0x18, 0x36, 0x7f, 0xfe, 0x6c, 0xdd, 0xff, 0x1f, 0xdc,
	0x9e, 0x79, 0xa0, 0x31, 0xb4, 0xce, 0xb3, 0x30, 0x6e, 0x3d, 0xcf, 0x62, 0xa7, 0xe3, 0xfe, 0x47,
	0x41, 0x69, 0x78, 0x16, 0x42, 0x0d, 0x5b, 0xd7, 0x89, 0x90, 0x9f, 0xb4, 0xaa, 0x55, 0x73, 0x63,
	0x56, 0xc4, 0x07, 0xa8, 0x3e, 0xed, 0x48, 0xae, 0x93, 0x93, 0xbe, 0x4a, 0x2a, 0xf3, 0xea, 0xe4,
	0xcb, 0x91, 0xde, 0xfc, 0xb9, 0xc8, 0xf8, 0x08, 0xe0, 0x29, 0xf0, 0xec, 0x7b, 0x7a, 0x1d, 0x74,
	0x91, 0xec, 0xbf, 0x9b, 0xf8, 0xd7, 0x86, 0x77, 0xe9, 0xc4, 0xf6, 0xba, 0xac, 0x55, 0x53, 0x99,
	0xcc, 0xfb, 0x6f, 0x05, 0xc5, 0x1b, 0x0f, 0x84, 0x08, 0x85, 0x67, 0x96, 0x94, 0xa9, 0x32, 0xe9,
	0x1c, 0xa3, 0x06, 0x3a, 0x9e, 0x69, 0x92, 0x25, 0xcf, 0x8a, 0xf8, 0x04, 0x65, 0x6c, 0x76, 0xc9,
	0xb2, 0x3b, 0xdc, 0xb7, 0x4b, 0xcf, 0x36, 0x75, 0x34, 0x17, 0x89, 0xcf, 0x50, 0xf5, 0x27, 0x3b,
	0x0e, 0x9e, 0x26, 0x5d, 0xd4, 0x9b, 0x66, 0x77, 0xb8, 0xcb, 0x0f, 0xe3, 0x50, 0x93, 0xf5, 0xc7,
	0x75, 0xda, 0xd7, 0xcb, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x1c, 0xaf, 0x2f, 0x3f, 0x01,
	0x00, 0x00,
}
